pub mod screenshot;
pub mod screen_state;
pub mod touch;
pub mod key_event;
pub mod text_input;
pub mod unlock_device;
pub mod sms;
pub mod sms_framework;
pub mod call;
pub mod call_framework;
pub mod shell;
pub mod filesystem;
pub mod ui_automation;
pub mod package_manager_tool;
pub mod memory_tool;
pub mod skills_tool;
pub mod delegate_tool;
pub mod sensors_tool;
pub mod wifi_tool;
pub mod audio_tool;
pub mod draw_tool;
pub mod web_tool;
pub mod ocr_tool;
pub mod brain_tool;
pub mod research_tool;
pub mod plan_tool;
pub mod bg_tool;

pub use screenshot::ScreenshotTool;
pub use touch::TouchTool;
pub use key_event::KeyEventTool;
pub use text_input::TextInputTool;
pub use sms::SmsTool;
pub use sms_framework::SmsFrameworkTool;
pub use call::CallTool;
pub use call_framework::CallFrameworkTool;
pub use shell::ShellTool;
pub use filesystem::FileSystemTool;
pub use ui_automation::UiAutomationTool;
pub use package_manager_tool::PackageManagerTool;
pub use memory_tool::MemoryTool;
pub use skills_tool::SkillsTool;
pub use delegate_tool::DelegateTool;
pub use unlock_device::UnlockDeviceTool;
pub use sensors_tool::SensorsTool;
pub use wifi_tool::WifiTool;
pub use audio_tool::AudioTool;
pub use draw_tool::DrawTool;
pub use web_tool::WebTool;
pub use ocr_tool::OcrTool;
pub use brain_tool::BrainTool;
pub use research_tool::ResearchTool;
pub use plan_tool::PlanTool;
pub use bg_tool::{new_tools_handle, BgTool, ToolsHandle};

#[cfg(test)]
mod tests;
