pub mod message;
pub mod tool;
pub mod budget;
pub mod compressor;
pub mod session;
pub mod prompt;
pub mod runtime;
pub mod mem_monitor;
pub mod memory;
pub mod skills;
pub mod cron;
pub mod scheduler;
pub mod user_model;
pub mod mcp;
pub mod task_queue;
pub mod brain;
pub mod motivation;
pub mod reflector;
pub mod life_loop;
pub mod curiosity;
pub mod goal;
pub mod gardener;
pub mod hardware;
pub mod call_pipeline;
pub mod notebook;

pub use message::{Message, ToolCall};
pub use tool::{Tool, ToolRegistry, ToolResult};
pub use budget::IterationBudget;
pub use compressor::ContextCompressor;
pub use session::SessionStore;
pub use prompt::SystemPrompt;
pub use runtime::{AgentRuntime, AgentResponse, StreamCallback};
pub use mem_monitor::{MemMonitor, MemStats};
pub use memory::{MemoryStore, Memory, MemoryCategory};
pub use skills::SkillStore;
pub use cron::CronExpr;
pub use scheduler::{Scheduler, ScheduledTask, TelegramSender};
pub use runtime::build_provider_helper;
pub use user_model::UserModel;
pub use mcp::{McpClient, McpServerConfig, register_mcp_tools};
pub use task_queue::{TaskQueue, TaskRequest, TaskSource, QueueStatus};
pub use brain::{DualBrain, BrainChoice, BrainMode};
pub use motivation::{Motivation, DriveEvent, LifeAction};
pub use reflector::{Reflector, Reflection, ReflectionOutcome, CompletedTask};
pub use life_loop::{LifeLoop, AutonomyState, Proposal, ProposalStatus};
pub use curiosity::Curiosity;
pub use goal::{GoalGenerator, Pattern, PatternKind};
pub use gardener::{GardenerConfig, spawn as spawn_gardener};
pub use hardware::{resolve_modem, DetectedHardware};
pub use call_pipeline::{CallStore, CallRecord, CallMetadata, spawn as spawn_call_pipeline};
pub use notebook::{BrainStats, BrainStore, Note, parse_wikilinks, slugify};

#[cfg(test)]
mod runtime_tests;
